### ISSUE TITLE
ERROR:  remote query result does not match the foreign table

### ISSUE THREAD

**Issue by loraxman** [jaiminpan/cassandra2_fdw#1]
I get this error when selecting a specific lists of columns that do not include all of the tables' columns.

Commenting out the 2 lines in cassandra2_fdw.c at 1016 seems to fix it.

**Comment by jaiminpan** [comment]
Thanks, I will check it later

2015-09-28 23:16 GMT+08:00 Roger Kelly notifications@github.com:

**Comment by jaiminpan** [comment]
this is fixed by commit 91bb6e6a586c97874ac02c49c614160160642208
