### ISSUE TITLE
Cassandra 3?

### ISSUE THREAD

**Issue by con-mo8** [jaiminpan/cassandra2_fdw#2]
Was just wondering if you have any interest or plan for updating to support the latest Cassandra version 3+? Would commits towards that be welcome?

**Comment by jaiminpan** [comment]
Yes, the idea of support Cassandra 3 sounds good. I believe i will do it
next time.
Of course, any commits is welcome. Thank you for your suggestion.

2016-05-31 21:58 GMT+08:00 Matt Oates notifications@github.com:
